name: Pull Request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  pull-request:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 18]

    name: 'Build: node-${{ matrix.node-version }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install deps
        run: pnpm i -no-frozen-lockfile

      - name: Unit test
        run: pnpm test
